name: Windows MinGW 64 build & test

on:
  push:
    branches: ["main"]

jobs:
  build-and-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install MinGW dependencies
        run: |
          pacman -Syu --noconfirm    # Met à jour pacman et le système
          pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain --noconfirm
        shell: bash
      - name: Generate visual Studio solution
        run: cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=C:\msys64\ucrt64\bin\gcc.exe -DCMAKE_CXX_COMPILER:FILEPATH=C:\msys64\ucrt64\bin\g++.exe -Btarget -G "MinGW Makefiles"
      - name: Build
        run: cmake --build target --config Release 
      - name: Test
        run: |
          cd target
          ctest -j10 -C Release -T test --output-on-failure
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Windows CityHash Test Report
          path: target/test/test_*_report.xml
          reporter: java-junit
      - name: Release
        run: |
          xcopy target\test\Release release\ /s /y
          xcopy target\src\Release release\ /s /y
          xcopy src\cityhash release\cityhash\ /s /y
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: windows_mingw_64
          path: release\**
